### ISSUE TITLE
Kill zombie process

### ISSUE THREAD

**Issue by RobbiNespu** [RobbiNespu/RadioMalaya#2]
After CTRL+C there still few mplayerrunning in background as zombie
```
 $ ps -ef | grep mplayer
rnm      26820 26803  0 01:00 pts/0    00:00:00 /usr/bin/mplayer http://radio.uthm.edu.my:8000/live.mp3
rnm      26837 26820  0 01:01 pts/0    00:00:00 /usr/bin/mplayer http://radio.uthm.edu.my:8000/live.mp3
```
How we can kill it when terminate the bash script?

**Comment by Jitsusama** [comment]
I should be able to handle this for ya.

**Comment by Jitsusama** [comment]
That PR should fix the issue for you. I've tested it on my machine and it seems to work fine.

**Comment by RobbiNespu** [comment]
Hey, thats great

**Comment by RobbiNespu** [comment]
Merged. Thank you for wonderful fix

**Comment by Jitsusama** [comment]
You’re so welcome, enjoy!
